name: Deploy to Staging

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # - name: Install dependencies
        # run: composer install --no-dev --optimize-autoloader
      # - name: Build assets
        # run: npm run production
      - name: Upload code to server
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          host: echogg.eu
          username: codex.echogg.eu
          password: ${{ secrets.ftp_password }}
          # source: ./
          server_dir: /echogg.eu/web
